[pytest]
pythonpath = .
norecursedirs = scripts venv .git __pycache__ storage .pytest_cache
filterwarnings =
    ignore::DeprecationWarning
    ignore::starlette.testclient.StarletteDeprecationWarning
