"""
AI & RAG Pydantic Data Structures for Part 7E: RAG + AI Recommendation & Evidence-Based Explanation
Defines structured evidence references, retrieved chunks, LLM outputs, and indexing summaries.
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field
from app.services.ai.ai_config import AIRecommendationEnum, ConfidenceLabelEnum, RAGSourceType


class EvidenceRef(BaseModel):
    """Structured evidence citation reference tied to an indexed source entity."""
    model_config = ConfigDict(from_attributes=True)

    source_type: str = Field(..., description="Entity type: COMPLIANCE_RESULT, VERIFICATION_RESULT, BID_DOCUMENT, etc.")
    source_id: str = Field(..., description="Database ID or unique code of the cited source entity")
    title: str = Field(..., description="Human-readable citation label (e.g. 'Local Content Compliance Result')")
    page: Optional[int] = Field(None, description="Document page number where evidence was located")
    rule_code: Optional[str] = Field(None, description="Requirement code associated with evidence (e.g. 'OEM-01')")
    summary: str = Field(..., description="Short factual excerpt or audit reason")


class RetrievedEvidence(BaseModel):
    """Representation of an individual chunk retrieved during vector/hybrid search."""
    model_config = ConfigDict(from_attributes=True)

    chunk_id: str
    source_type: str
    source_id: str
    document_id: Optional[str] = None
    content: str
    similarity_score: float
    page_number: Optional[int] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class AIRecommendationOutput(BaseModel):
    """Structured output generated by LLM and validated by guardrails for Bid evaluation."""
    model_config = ConfigDict(from_attributes=True)

    summary: str = Field(..., description="High-level executive summary of bid evaluation status")
    strengths: List[str] = Field(default_factory=list, description="Key verified compliant items")
    concerns: List[str] = Field(default_factory=list, description="Deterministic failures, high risks, or mismatches")
    review_items: List[str] = Field(default_factory=list, description="Items requiring Procurement Officer inspection")
    recommendation: AIRecommendationEnum = Field(..., description="Non-binding recommendation enum")
    recommendation_reason: str = Field(..., description="Direct factual rationale for the recommendation")
    evidence_refs: List[EvidenceRef] = Field(default_factory=list, description="Grounded citations")
    confidence_label: ConfidenceLabelEnum = Field(default=ConfidenceLabelEnum.MEDIUM, description="HIGH, MEDIUM, LOW")
    limitations: List[str] = Field(default_factory=list, description="Data boundaries or pending checks")


class AIQuestionAnswerOutput(BaseModel):
    """Structured response for interactive Procurement Officer Q&A on a specific Bid."""
    model_config = ConfigDict(from_attributes=True)

    question: str
    answer: str
    evidence_refs: List[EvidenceRef] = Field(default_factory=list)
    limitations: List[str] = Field(default_factory=list)


class RAGIndexResult(BaseModel):
    """Summary metrics of knowledge chunks generated and stored for a Tender / Bid."""
    model_config = ConfigDict(from_attributes=True)

    tender_id: str
    bid_id: Optional[str] = None
    total_chunks_created: int
    source_breakdown: Dict[str, int] = Field(default_factory=dict)
